### ISSUE TITLE
使用思源系列字体

### ISSUE THREAD

**Issue by meijieru** [skinaze/HUSTPaperTemp#11]
linux下字体问题还挺麻烦的。思源系列字体还是非常好获取/安装的，同时没有任何版权问题，能否提供一个思源系列字体的选项呢

**Comment by skinaze** [comment]
这个提议不错，我会在下个版本提供这个功能

**Comment by skinaze** [comment]
下一个版本我可能要稍微推迟一下，我想把对思源字体的支持加入到下个更新中，我已经向CTAN提交了思源字体，但是在texlive支持上有点问题，解决之后我再发布

**Comment by meijieru** [comment]
thx，我先下个中宋苟一下

**Comment by skinaze** [comment]
最近有点忙，我先加了一个临时的思源字体的支持，不过需要手动安装字体到系统，目前只测试了Windows系统的兼容性，我会后期再更新

思源字体现在可以从CTAN上下载了：[https://ctan.org/pkg/notocjksc](https://ctan.org/pkg/notocjksc)

**Comment by meijieru** [comment]
thx, 我系统中安装了 adobe-source-han-sans 和 adobe-source-han-serif，是不是要手动指定一下？

**Comment by skinaze** [comment]
半个月不在电脑前，抱歉
最好用Noto字体而不是adobe-source-han，字体名不同会造成不识别

**Comment by meijieru** [comment]
好的，多谢lz
