### ISSUE TITLE
调整图表和正文间距

### ISSUE THREAD

**Issue by meijieru** [skinaze/HUSTPaperTemp#12]
图表位于顶部或者底部时和正文间距不对。也不能通过 `\vspace` 调节（结果非常怪异，貌似把图片和之后的正文看作一部分了）

**Comment by skinaze** [comment]
这是由于我宏包中设置了
\setlength{\textfloatsep}{0pt}
这个命令修改文字和浮动体之间的距离，当设置浮动体为在这里时，文字与浮动体之间的间距应该是由于行间距造成的

参考你的意见，我会在下个版本设置为
\setlength{\textfloatsep}{6pt}
但是这样仍然能够看出“在这里”的浮动体与文字间的距离比在“在顶部”和“在底部”的浮动体与文字间的距离要略大

我有空再看看有没有其他结局方案

**Comment by meijieru** [comment]
好的，多谢lz。不知道能否透露一下个版本的时间呢

**Comment by skinaze** [comment]
这周应该能发，你着急可以直接在引言部分用这条命令修改

**Comment by meijieru** [comment]
thx
