### ISSUE TITLE
参考文献中作者的名字都是大写

### ISSUE THREAD

**Issue by cxmscb** [skinaze/HUSTPaperTemp#13]
你好，参考文献中作者的名字都是大写，应该改为是首字母大写吧。

**Comment by skinaze** [comment]
这个问题在使用说明3.7章已经说明了，我的模板默认使用了GBT7714-2005的国标样式，与学校模板给的参考文献样式不完全一样，考虑到官方模板没有给出明确的样式要求，使用国标是没有什么明显的问题的

**Comment by skinaze** [comment]
如果喜好的话，可以选择使用清华大学的参考文献样式，使用
`\documentclass[supercite,tsinghuacite]{HustGraduPaper}`
即可

PS. 我刚注意到清华大学的论文升级导致我原来的选项出现了问题，请等待下一个版本再这样用

**Comment by skinaze** [comment]
新版本已经发布，注意删掉编译临时文件再重新编译才能看到新的参考文献格式
