### ISSUE TITLE
数学公式相关

### ISSUE THREAD

**Issue by meijieru** [skinaze/HUSTPaperTemp#15]
在这个模板中 `$ \mathrm{\Delta} $` 会产生白框，在其他模板中不会。可能是字体原因？

**Comment by skinaze** [comment]
初步判断这是由于ctex宏包造成的，我不太确定你用这个表达方式是什么目的？本身希腊字母大写就是罗马体的形式啊。我尝试对比了一下什么宏包都不加载情况下的`\mathrm{\Delta}`和`\Delta`，并没有可见区别。

**Comment by meijieru** [comment]
之前用的别的模板不加 `\mathrm` 的话会是斜体的，去掉之后貌似正常了。

**Comment by meijieru** [comment]
另一个问题，在 equation 环境前加空行后间距不正常。

**Comment by skinaze** [comment]
不太明白你的意思，为什么要在equation环境前后加空行？间距不正常是怎么不正常了？

**Comment by meijieru** [comment]
比如

```latex
{正文}
{空行}
{公式}
```
这样生成的pdf正文与公式之间会有一个额外的空行

如果使用
```latex
{正文}
{公式}
```
就是正常的结果

**Comment by skinaze** [comment]
这个很正常啊，什么宏包都不加载也是这样啊。我感觉这个空行应该是被视为新的段落了，至于新的段落为什么会有空行我不清楚。正常而言也不会新起一段开头就是公式吧？

**Comment by meijieru** [comment]
这样啊，之前我用的一个模板不是这样的。主要是我一般公式单独列出来，前后都会留空行，个人习惯。

**Comment by skinaze** [comment]
你那是什么模板，有毒啊

**Comment by meijieru** [comment]
eccv。。。
