### ISSUE TITLE
caption和图片/表格间距

### ISSUE THREAD

**Issue by meijieru** [skinaze/HUSTPaperTemp#16]
现在模板里两者间距是 `0pt`，不是很美观，看了一下word模板，也是有一定间距的

**Comment by Mein-Fuhrer** [comment]
`\setlength{\belowcaptionskip}{5pt}`
试下

**Comment by meijieru** [comment]
这样是可以，但每张图都需要加，比较麻烦

```
\captionsetup[figure]{position=bottom,skip={2pt}}
\captionsetup[table]{position=top,skip={2pt}}
```

目前直接改的模板

**Comment by skinaze** [comment]
这个问题不同人的喜好不同，所以我就不改我自己的模板了，这两条命令可以在引言部分使用，这样就能覆盖模板相关设定了
