### ISSUE TITLE
如何增加标题层级

### ISSUE THREAD

**Issue by QYQSDTC** [skinaze/HUSTPaperTemp#2]
这个模版只能到subsubsection，怎样增加一个subsubsubsection
关于首行缩进问题可以
\RequirePackage{indentfirst}
\setlength{\parindent}{2em}
MacTex 2016 测试可以

**Comment by skinaze** [comment]
\subsubsubsection已经在v2.1.0中提供了支持，首行缩进的问题已经解决，使用这之后的版本就可以啦~
