### ISSUE TITLE
约化普朗克常数（$\hbar$）显示有误。

### ISSUE THREAD

**Issue by KevinWangT** [skinaze/HUSTPaperTemp#20]
你好，我在我的电脑上使用这一模板时发现约化普朗克常数的符号显示有误，具体情况可见下图：
![1](https://user-images.githubusercontent.com/15872396/57056255-c9242800-6cd3-11e9-9f91-f319343c3a00.png)
正确的显示应为：
![2](https://user-images.githubusercontent.com/15872396/57056290-07b9e280-6cd4-11e9-98de-f54d74b5a8f1.png)

在我这里可以复现这一状况的代码如下：
```latex
\documentclass[supercite]{HustGraduPaper}
%进行个人信息设置
\title{论文题目} %论文题目
\author{作者姓名} %作者姓名
\date{\today} %日期，默认当日
\school{院系名称} %院系名称
\classnum{专业班级} %专业班级
\stunum {U201300000} %学号
\instructor{指导教师姓名} %指导教师姓名

%添加自己要用的其他宏包


\begin{document}
	
	\section{第一节}
	这里有一个问题，那就是 \verb|\hbar| 命令生成的约化普朗克常数符号中的横线的位置并不对，横线应该与 \verb|h| 的竖线相交（类似于 \verb|\hslash|），而不是在字母 h 的上方（类似 \verb|\bar{h}| 这样）。
	\begin{itemize}
		\item \verb|\hbar|:$ \hbar $
		\item \verb|\hslash|：$ \hslash $
		\item \verb|\bar{h}|:$ \bar{h} $
	\end{itemize}
\end{document}
```

相关信息：

- HUSTPaperTemp 版本：2.1.8
- 操作系统：Arch Linux
- 所安装的 TexLive 版本：
![tex](https://user-images.githubusercontent.com/15872396/57056407-ea394880-6cd4-11e9-9591-c73d9d02881d.png)

- 文本编辑器： Texstudio
- 构建命令：
![build](https://user-images.githubusercontent.com/15872396/57056362-9f1f3580-6cd4-11e9-861a-bf46c96877c1.png)
- 编译命令：
![compile](https://user-images.githubusercontent.com/15872396/57056368-a7777080-6cd4-11e9-8b56-e1ae06472ff3.png)

**Comment by skinaze** [comment]
这个是由于fontspec宏包造成的，首先CTEX宏包使用了fontspec宏包，却没有使用no-math选项，这导致我为了满足模板使用Times New Roman字体的要求，使用fontspec宏包`\setmainfont{Times New Roman}`命令更改字体时，改掉了公式字体。我尝试了使用`\PassOptionsToPackage{no-math}{fontspec}`命令使fontspect不改变公式字体，但是没有作用。

我现在能找到的比较好的解决方案就是用一个数学字体宏包（比如unicode-math，mathpazo）定义具体的数学字体。具体使用方法在引言部分引入
`\usepackage{unicode-math}`
或者
`\usepackage{mathpazo}`

你看看这样能否解决你的问题

**Comment by KevinWangT** [comment]
可以，麻烦你了，谢谢。
