### ISSUE TITLE
mac下封面无法使用华文中宋，参考文献网址无法换行

### ISSUE THREAD

**Issue by sawyeron** [skinaze/HUSTPaperTemp#6]
mac虽然可以在word中直接使用华文中宋字体，但是该字体并未安装到“字体册”中，建议做相关修改。暂时用的是华文宋体。

参考文献中如果存在网址的，一般都会超出页面，无法换行，现在是用网上找的一个7714-2015样式替换了7714-2005

此外，脚注的序号应当每页重新从1计算，加入`\usepackage[perpage]{footmisc}`

**Comment by skinaze** [comment]
1. 我会尽快验证这个问题
2. 这个样式我已经加入了宏包选项
3. 这个问题已经修复

**Comment by skinaze** [comment]
1. 这个问题我在安装2016版本后也出现了，目前已经在更新的使用说明中添加了脚注说明解决方法

**Comment by sawyeron** [comment]
棒！另外，关于章节序号可以做定义吗？就是把标题从"1 XXX"，换成“第一章 XXX”。

**Comment by skinaze** [comment]
这个是你们院系的要求吗？还是你期望这样使用？
如果是后者直接在引言中设置ctex宏包如下：
`\ctexset{section={name={第,节},number=\chinese{section},}}`

**Comment by sawyeron** [comment]
文科类论文的标题样式，按“章-->节-->标题一-->标题（一）“来要求的

**Comment by skinaze** [comment]
方便把你手里的模板发一份给我吗[me@stringblog.com](mailto:me@stringblog.com)

**Comment by sawyeron** [comment]
你是说学院的标准模版吗？

**Comment by Keithnier** [comment]
大佬，封面生成失败，需要改哪啊，内容只有华中科技大学，论文题目和学号，其他内容都没出来

**Comment by sawyeron** [comment]
@Keithnier 报错的内容是啥

**Comment by Keithnier** [comment]
@sawyeron 一堆错误。。我也不知道怎么描述。。。我再看看吧。。脑壳疼，被虐哭了

**Comment by skinaze** [comment]
@sawyeron 是的，你们学院的模板，我看一下差别在哪里

**Comment by skinaze** [comment]
@Keithnier 你的编译有问题的话再开个新的issue吧，把你的报错代码列出来

**Comment by Keithnier** [comment]
@skinaze 我看了一下，解决了，还是Mac下字体问题。。我把华文中宋改成STsong，应该是STSong。。。感谢大佬的模版

**Comment by sawyeron** [comment]
@skinaze 你好，今天才看到你后面的回复。已发送你邮箱，麻烦你帮我看下吧，谢谢。

**Comment by Lyrichu** [comment]
> @skinaze 我看了一下，解决了，还是Mac下字体问题。。我把华文中宋改成STsong，应该是STSong。。。感谢大佬的模版

请问一下，具体在模板里面是怎么改的呢?现在我也碰到了这个问题，报 STSzhongsong找不到这个字体。谢谢!

**Comment by Lyrichu** [comment]
> > @skinaze 我看了一下，解决了，还是Mac下字体问题。。我把华文中宋改成STsong，应该是STSong。。。感谢大佬的模版
> 
> 请问一下，具体在模板里面是怎么改的呢?现在我也碰到了这个问题，报 STSzhongsong找不到这个字体。谢谢!

我刚才又试了一下，是因为我本机没有安装华文中宋字体的原因，从网上搜索到这个字体，然后安装，再编译封面就没有报错了，封面也可以正常显示。
