### ISSUE TITLE
win10 texworks编译example遇到问题

### ISSUE THREAD

**Issue by YoungDreamerer** [skinaze/HUSTPaperTemp#8]
在多台电脑上使用均遇到这个问题，请问怎么解决？

(D:\CTEX\MiKTeX\tex\latex\fontspec\fontspec.sty
(D:\CTEX\MiKTeX\tex\latex\l3packages\xparse\xparse.sty)

! LaTeX Error: Unknown option `AutoFakeBold=true' for package `fontspec'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

**Comment by skinaze** [comment]
请注意关于依赖宏包的版本问题，在使用模板前建议更新所有宏包
