### ISSUE TITLE
外校同学请求参(zhao)考(chao)该模板

### ISSUE THREAD

**Issue by IonizingRadiation** [skinaze/HUSTPaperTemp#9]
@skinaze 您好，
我是某渣校同学，偶然看到您的模板，感觉简单易懂，萌生了对其魔改以适用本渣校论文要求的想法，不知作者意向如何？

另外，我会遵照 MIT License 的要求，在本渣校模板的开头注释处保留您的相关声明，如果您同意的话。

不胜感激。

**Comment by skinaze** [comment]
可以的，建议你直接Fork一下好了~

**Comment by IonizingRadiation** [comment]
OK，感谢作者
